-- ENDF Reports table and seed data
-- Scraped from https://www.nndc.bnl.gov/endfdocs/

CREATE TABLE IF NOT EXISTS endf_reports (
  id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  seq_number      INT NOT NULL,
  report_number   TEXT NOT NULL UNIQUE,
  authors         TEXT,
  title           TEXT NOT NULL,
  report_date     TEXT,
  cross_reference TEXT,
  pdf_url         TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_endf_reports_seq ON endf_reports(seq_number);
CREATE INDEX IF NOT EXISTS idx_endf_reports_number ON endf_reports(report_number);

GRANT SELECT ON endf_reports TO anon;

-- 316 reports
INSERT INTO endf_reports (seq_number, report_number, authors, title, report_date, cross_reference, pdf_url) VALUES
  (315, 'ENDF-379', 'Dermott E. Cullen', 'A Survey of ENDF/B-VIII Resonance Parameters (MF=2)', 'Nov. 2020', 'INDC(NDS)-0819', 'https://www.nndc.bnl.gov/endfdocs/ENDF-379.pdf'),
  (314, 'ENDF-378', 'CSEWG Covariance Committee', 'Guidance on Generating Neutron Reaction Data Covariances for the ENDF/B Library', '2011', '', 'https://www.nndc.bnl.gov/endfdocs/ENDF-378.pdf'),
  (313, 'ENDF-377', 'Donald L. Smith', 'Quality Assurance Requirements for ENDF/B-VII.1 Covariances', '2011', '', 'https://www.nndc.bnl.gov/endfdocs/ENDF-377.pdf'),
  (312, 'ENDF-376', 'Russell D. Mosteller', 'An Expanded Criticality Validation Suite for MCNP', '2010', 'LA-UR-10-06230', 'https://www.nndc.bnl.gov/endfdocs/ENDF-376.pdf'),
  (311, 'ENDF-375', 'V. Sobes, L. Leal, G. Arbanas', 'User''s Guide To SAMINT: A Code For Nuclear Data Adjustment With SAMMY Based On Integral Experiments', 'Aug 2014', 'ORNL/TM-2014/245', 'https://www.nndc.bnl.gov/endfdocs/ENDF-375.pdf'),
  (310, 'ENDF-374', 'D.E. Cullen', 'How Accurate Are Our Processed ENDF Cross Sections?', 'May 2014', 'INDC(NDS)-0666', 'https://www.nndc.bnl.gov/endfdocs/ENDF-374.pdf'),
  (309, 'ENDF-373', 'D.E. Cullen', 'PROGRAM ENDF2C: Convert ENDF Data to Standard FORTRAN, X and C++ Format (Version 2014-1) (The code is available here)', 'Apr 2014', 'IAEA-NDS-217', 'https://www.nndc.bnl.gov/endfdocs/ENDF-373.pdf'),
  (308, 'ENDF-372', 'D.E. Cullen', 'ENDF/X: an Extended ENDF Format (Evolution, not Revolution)', 'Dec 2012', 'INDC(NDS)-0659', 'https://www.nndc.bnl.gov/endfdocs/ENDF-372.pdf'),
  (307, 'ENDF-371', 'D.E. Cullen', 'ENDF/B-VII.1 vesus ENDF/B-VII.0: What''s Different?', 'Mar 2012', 'LLNL-TR-548633', 'https://www.nndc.bnl.gov/endfdocs/ENDF-371.pdf'),
  (306, 'ENDF-370', 'D.E. Cullen', 'Doppler Broadening Update: Broadening near the Unresolved Resonance Region', 'Jan 2012', 'LLNL-TR-534931', 'https://www.nndc.bnl.gov/endfdocs/ENDF-370.pdf'),
  (305, 'ENDF-369', 'D.E. Cullen', 'A Short History of ENDF/B Unresolved Resonance Parameters', 'Oct 2010', 'LLNL-TR-461199', 'https://www.nndc.bnl.gov/endfdocs/ENDF-369.pdf'),
  (304, 'ENDF-368', 'D.E. Cullen', 'ENDF Cross Sections are not Uniquely Defined', 'June 2010', 'LLNL-TR-446331', 'https://www.nndc.bnl.gov/endfdocs/ENDF-368.pdf'),
  (303, 'ENDF-367', 'N.M. Larson', 'SAMMY User Guidance for ENDF Formats', 'Mar-07', 'ORNL/TM-2007/23', 'https://www.nndc.bnl.gov/endfdocs/ENDF-367.pdf'),
  (302, 'ENDF-366', 'F.B.Guimaraes, C.Y.Fu, L.C.Leal', 'Nuclear cross-section calculations in the 1 MeV to 5 GeV range with combined semi-classical and quantum mechanical models', 'Feb-2002', 'ORNL/TM-2001/191', 'https://www.nndc.bnl.gov/endfdocs/ENDF-366.pdf'),
  (301, 'ENDF-365', 'L.C.Leal, H.Derrien, J.A.Harvey, K.H.Guber, N.M.Larson, R.R.Spencer', 'R-Matrix resonance analysis and statistical properties of the resonance parameters of 233U in the neutron energy range from thermal to 600 eV', 'Mar-2001', 'ORNL/TM-2000/372', 'https://www.nndc.bnl.gov/endfdocs/ENDF-365.pdf'),
  (300, 'ENDF-364-R1', 'N.M. Larson', 'Updated Users'' Guide for SAMMY: Multilevel R-matrix ...', 'Sep-06', 'ORNL/TM-9179/R7', 'https://www.nndc.bnl.gov/endfdocs/ENDF-364-R1.pdf'),
  (299, 'ENDF-363', 'O. Bouland, R. Babut, N.M. Larson', 'SAMQUA - A program for Generating All Possible Combinations of Quantum Numbers Leading to the Same Compound Nucleus State in the Framework of the R-Matrix Code SAMMY', 'Apr-02', 'JEF-DOC 929 OECD/NEA Publications', 'http://www.oecd-nea.org/dbdata/nds_jefdoc/jefdoc-929.pdf'),
  (298, 'ENDF-362', 'Soo-Youl Oh, Jonghwa Chang, S. Mughabghab', 'Neutron Cross Section Evaluations of Fission Products Below the FastEnergy Region', 'Apr-00', 'BNL-NCS-67469', 'https://www.nndc.bnl.gov/endfdocs/ENDF-362.pdf'),
  (297, 'ENDF-358', 'W.P. Poenitz, S.E. Aumeier', 'The Simultaneous Evaluation of the Standards and Other Cross Sections ofImportance for Technology', 'Sep-97', 'ANL/NDM-139', 'https://www.nndc.bnl.gov/endfdocs/ENDF-358.pdf'),
  (296, 'ENDF-XXX', 'R.E. Miller, D.L. Smith', 'A Compilation of Information on the 32S(p,g)33Cl Reaction and Propertiesof Excited Levels in 33CL', 'Jul-97', 'ANL/NDM-143', 'https://www.nndc.bnl.gov/endfdocs/ENDF-XXX.pdf'),
  (295, 'ENDF-356', 'R.E. MacFarlane', 'New Thermal Neutron Scattering Files for ENDF/B-VI Release 2', 'Mar-94', 'LA-12639-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-356.pdf'),
  (294, 'ENDF-355', 'M.C. Moxon', 'Comments on the ENDF/B-VI Evaluation for 235-U in the Neutron EnergyRegion from 1 to 20 eV', 'Feb-93', 'ORNL/TM-12304', 'https://www.nndc.bnl.gov/endfdocs/ENDF-355.pdf'),
  (293, 'ENDF-354', 'L.W.Weston, D.C.Larson', 'Compilation of Requests for Nuclear Data', 'Jan-93', 'ORNL/TM-12291', 'https://www.nndc.bnl.gov/endfdocs/ENDF-354.pdf'),
  (292, 'ENDF-353', 'E.J.Axton', 'An Evaluation of Kerma in Carbon and the Carbon Cross Sections', 'Feb-92', 'NISTIR 4838', 'https://www.nndc.bnl.gov/endfdocs/ENDF-353.pdf'),
  (291, 'ENDF-352', 'J. Katakura, T.R. England', 'Augmentation of ENDF/B Fission Product Gamma-Ray Spectra by Calculated Spectra', 'Nov-91', 'LA-12125-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-352.pdf'),
  (290, 'ENDF-351', 'A.D. Carlson, W.P. Poenitz, G.M. Hale, et al.', 'The ENDF/B-VI Neutron Cross Section Measurements Standards', 'May-93', 'NISTIR 5177', 'https://www.nndc.bnl.gov/endfdocs/ENDF-351.pdf'),
  (289, 'ENDF-350', 'D.M. Hetrick, D.C. Larson, C.Y. Fu', 'Generation of Covariance Files for the Isotopes of Cr, Fe, Ni, Cu, and Pb in ENDF/B-VI', 'Feb-91', 'ORNL/TM-11763', 'https://www.nndc.bnl.gov/endfdocs/ENDF-350.pdf'),
  (289, 'ENDF-349', 'T.R.England, B.F.Rider', 'Evaluation and Compilation of Fission Product Yields', 'Oct-94', 'LA-UR-94-3106', 'https://www.nndc.bnl.gov/endfdocs/ENDF-349.pdf'),
  (288, 'ENDF-347', 'C.M. Perey, F.G. Perey, J.A. Harvey, et al.', '58Ni+n Transmission, Differential Elastic Scattering and Capture Measurements and Analysis from 5 to 813 KeV', 'Sep-88', 'ORNL/TM-10841', 'https://www.nndc.bnl.gov/endfdocs/ENDF-347.pdf'),
  (287, 'ENDF-346', 'D.M. Hetrick, C.Y. Fu, D.C. Larson', 'Calculated Neutron-Induced Cross Sections for 52-Cr from 1 to 20MeV andComparisons with Experiments', 'Sep-87', 'ORNL/TM-10417', 'https://www.nndc.bnl.gov/endfdocs/ENDF-346.pdf'),
  (286, 'ENDF-345', 'K. Shibata, D.M. Hetrick', 'Calculated Neutron-Induced Cross Sections for 53-Cr from 1 to 20 MeV', 'May-87', 'ORNL/TM-10381', 'https://www.nndc.bnl.gov/endfdocs/ENDF-345.pdf'),
  (285, 'ENDF-344', 'D.M. Hetrick, C.Y. Fu, D.C. Larson', 'Calculated Neutron-Induced Cross Sections for 58,60-Ni from 1 to 20 MeV and Comparisons with Experiments', 'Jun-87', 'ORNL/TM-10219', 'https://www.nndc.bnl.gov/endfdocs/ENDF-344.pdf'),
  (284, 'ENDF-343', 'L.W. Weston, E.D. Arthur', 'Evaluation of the Neutron Cross Sections for PU-240', 'Apr-87', 'ORNL/TM-10386', 'https://www.nndc.bnl.gov/endfdocs/ENDF-343.pdf'),
  (283, 'ENDF-342', 'M.S. Milgram, S. Thompson, R. Paulson', 'Few Group Cross Sections for 274 Nuclides Based on ENDF/B-V', 'Feb-87', 'CRNL-2916', 'https://www.nndc.bnl.gov/endfdocs/ENDF-342.pdf'),
  (282, 'ENDF-341', 'C.Y. Fu, D.M. Hetrick', 'Update of ENDF/B-V Mod-3 Iron: Neutron Producting Reaction Cross Sections and Energy-Angle Correlations', 'Jul-86', 'ORNL/TM-9964', 'https://www.nndc.bnl.gov/endfdocs/ENDF-341.pdf'),
  (281, 'ENDF-340', 'D.W. Muir', 'Analysis of Central Worths and Other Integral Data from the Los Alamos Benchmark Assemblies', 'Oct-84', 'LA-10230-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-340.pdf'),
  (280, 'ENDF-339', 'N.M. Larson', 'Updated Users'' Guide for SAMMY: Multilevel R-Matrix Fits to Neutron...', 'Jun-76', 'ORNL/TM-9179/R1', ''),
  (279, 'ENDF-338', 'D.K. Olsen', 'Report to the 238U Discrepancy Task Force on SIOB Fits to the ORNL, CBNM,and JAERI Transmission Data', 'May-84', 'ORNL/TM-9023', 'https://www.nndc.bnl.gov/endfdocs/ENDF-338.pdf'),
  (278, 'ENDF-337', 'D.M. Hetrick, C.Y. Fu, D.C. Larson', 'Calculated Neutron-Induced Cross Sections for 63,65Cu from 1 to 20 MeV and Comparisons with Experiments', 'Aug-84', 'ORNL/TM-9083', 'https://www.nndc.bnl.gov/endfdocs/ENDF-337.pdf'),
  (277, 'ENDF-336', 'E.D. Arthur, P.G. Young, D.G. Madland, R.E. MacFarlane', 'Evaluation of n + 239Pu Nuclear Data for Revision 2 of ENDF/B-V', 'Oct-83', 'LA-9873-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-336.pdf'),
  (276, 'ENDF-335', 'R.W. Roussin, J.R. Knight, J.H. Hubbell, R.J. Howerton', 'Description of the DLC-99/HUGO Package of Photon Interaction Data in ENDF/B-V Format', 'Dec-83', 'ORNL/RSIC-46', 'https://www.nndc.bnl.gov/endfdocs/ENDF-335.pdf'),
  (275, 'ENDF-334', 'D.C. Larson, N.M. Larson, J.A. Harvey', 'ORELA Flight Path 1: Determinations of Its Effective Length vs Energy., Experimental Energies, and Energy Resolution Function and Their Uncertainties', 'Jun-84', 'ORNL/TM-8880', 'https://www.nndc.bnl.gov/endfdocs/ENDF-334.pdf'),
  (274, 'ENDF-333', 'D.C. Larson, N.M. Larson, J.A. Harvey, et al.', 'Application of New Techniques to ORELA Neutron Transmission Measurementsand their Uncertainty Analysis: The Case of Natural Nickel ...', 'Oct-83', 'ORNL/TM-8203', 'https://www.nndc.bnl.gov/endfdocs/ENDF-333.pdf'),
  (273, 'ENDF-332', 'T.R. England', 'ENDF/B-V Summary Data for Fission and Actinides', '', 'Not published', ''),
  (272, 'ENDF-331', 'R.W. Peelle, T.W. Burrows', 'An Annotated Bibliography Covering Generation and Use of Evalusted Cross Section Uncertainty Files', 'Mar-83', 'BNL-NCL-51684', 'https://www.nndc.bnl.gov/endfdocs/ENDF-331.pdf'),
  (271, 'ENDF-330', 'C.M. Perey, J.A. Harvey, R.L. Macklin, et al.', 'Neutron Transmission and Capture Measurements and Analysis of 60Ni from 1 to 450 keV', 'Nov-82', 'ORNL-5893', 'https://www.nndc.bnl.gov/endfdocs/ENDF-330.pdf'),
  (270, 'ENDF-329', 'P.F. Rose', 'Symposium Proceedings: Thermal Reactor Benchmark Calculation...', '', '', ''),
  (269, 'ENDF-328', 'B.A. Magurno, R.R. Kinsey, F.M. Scheffel', 'Guidebook for the ENDF/B-V Nuclear Data Files', 'Jul-82', 'EPRI NP-2510', ''),
  (268, 'ENDF-327', 'C.R. Weisbin, D. Gilai, G. deSaussure, R.T. Santoro', 'Meeting Cross Section Requirements for Nuclear Energy Design', 'Jul-82', 'ORNL/TM-8220', 'https://www.nndc.bnl.gov/endfdocs/ENDF-327.pdf'),
  (267, 'ENDF-326', 'D.M. Hetrick, C.Y. Fu, D.C. Larson', 'Evaluated Neutron-Induced Cross Sections for 40-Ca from 20 to 40 MeV', 'Sep-82', 'ORNL/TM-8290', 'https://www.nndc.bnl.gov/endfdocs/ENDF-326.pdf'),
  (266, 'ENDF-325', 'C.Y. Fu', 'Summary of ENDF/B-V Evaluations for Carbon, Calcium, Iron, Copper, and Lead and ENDF/B-V Rev.2 for Calcium and Iron', 'Sep-82', 'ORNL/TM-8283', 'https://www.nndc.bnl.gov/endfdocs/ENDF-325.pdf'),
  (265, 'ENDF-324 Vol.4', 'D.W. Muir, R.E. MacFarlane', 'The NJOY Nuclear Data Processing System, Volume IV: The ERRORR and COVR Modules', 'Dec-85', 'LA-9303-M Vol.4', 'https://www.nndc.bnl.gov/endfdocs/ENDF-324-Vol4.pdf'),
  (264, 'ENDF-324 Vol.3', 'R.E. MacFarlane, D.W. Muir', 'The NJOY Nuclear Data Processing System, Volume III: The GROUPR, GAMINR, and MODER Modules', 'Oct-85', 'LA-9303-M Vol.3', 'https://www.nndc.bnl.gov/endfdocs/ENDF-324-Vol3.pdf'),
  (263, 'ENDF-324 Vol.2', 'R.E. MacFarlane, D.W. Muir, R.M. Boicourt', 'The NJOY Nuclear Data Processing System, Volume II: The NJOY, RECONR,BROADR, HEATR, AND THERMR Modules', 'May-82', 'LA-9303-M Vol.2', 'https://www.nndc.bnl.gov/endfdocs/ENDF-324-Vol2.pdf'),
  (262, 'ENDF-324 Vol.1', 'R.E. MacFarlane, D.W. Muir, R.M. Boicourt', 'The NJOY Nuclear Data Processing System, Volume 1: User''s Manual', 'May-82', 'LA-9303-M Vol.1', 'https://www.nndc.bnl.gov/endfdocs/ENDF-324-Vol1.pdf'),
  (261, 'ENDF-323', 'N.M. Larson', 'User''s Guide for BAYES: A General-Purpose Computer Code for Fitting a Functional Form to Experimental Data', 'Aug-82', 'ORNL/TM-8185', 'https://www.nndc.bnl.gov/endfdocs/ENDF-323.pdf'),
  (260, 'ENDF-322 #2', 'B.F. Rider', 'Compilation of Fission Products Yields (Microfiche Only)', 'Sep-80', 'NEDO 12154-3(C)', ''),
  (259, 'ENDF-322 #1', 'T.R. England, W.B. Wilson, R.E. Schenter, F.M. Mann', 'Summary of ENDF/B-V Data for Fission Products and Actinides', 'Dec-84', 'EPRI NP 3787 LA-UR 83-1285', 'https://www.nndc.bnl.gov/endfdocs/ENDF-322-1.pdf'),
  (258, 'ENDF-321', 'D.G. Madland', 'New Fission Neutron Spectrum Representation for ENDF', 'Apr-82', 'LA-9285-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-321.pdf'),
  (257, 'ENDF-320', 'R.J. LaBauve, T.R. England, D.C. George', 'Integral Data Testing of ENDF/B Fission Product Data and Comparisons of ENDF/B with other Fission Product Data Files', 'Nov-81', 'LA-9090-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-320.pdf'),
  (256, 'ENDF-319', 'D.K. Olsen', 'An Evaluation of the Resolved-Resonance-Region Cross Sections of 232Th', 'Mar-82', 'ORNL/TM-8056', 'https://www.nndc.bnl.gov/endfdocs/ENDF-319.pdf'),
  (255, 'ENDF-318', 'R.B. Kidman', 'Los Alamos Benchmarks: Calculations Based on ENDF/B-V Data', 'Nov-81', 'LA-9037-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-318.pdf'),
  (254, 'ENDF-317', 'M.A. Bjerke, C.C. Webster', 'Neutron Cross Section Libraries in the AMPX Master Interface Format for Thermal and Fast Reactors', 'Dec-81', 'ORNL/CSD/TM-164', 'https://www.nndc.bnl.gov/endfdocs/ENDF-317.pdf'),
  (253, 'ENDF-316', 'F.M. Mann', 'FTR Set 500, A Multigroup Cross-Section Set for FTR Analysis', 'Feb-82', 'HEDL-TME81-31', 'https://www.nndc.bnl.gov/endfdocs/ENDF-316.pdf'),
  (252, 'ENDF-315', 'R. Gwin, R.R. Spencer, R.W. Ingle', 'Measurement of the Average Number of Prompt Neutrons Emitted per Fissionof 233-U Relative to 252-Cf ...', 'Nov-81', 'ORNL/TM-7988', 'https://www.nndc.bnl.gov/endfdocs/ENDF-315.pdf'),
  (251, 'ENDF-314', 'R.B. Kidman', 'ENDF/B-V, LIB-V, CSEWG Benchmarks', 'Aug-81', 'LA-8950-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-314.pdf'),
  (250, 'ENDF-313', 'CSEWG Data Testing Committee', 'Benchmark Testing of ENDF/B Data for Thermal Reactors', 'Jul-81', 'BNL-NCS-29891', ''),
  (249, 'ENDF-312', 'G. De Saussure', 'Representation of the Neutron Cross Sections of Several Fertile and...', 'Sep-81', 'ORNL/TM-7945', ''),
  (248, 'ENDF-311', 'C.R. Weisbin, R.D. McKnight, J. Hardy Jr., et al.', 'Benchmark Data Testing of ENDF/B-V', 'Aug-82', 'BNL-NCS-31531', ''),
  (247, 'ENDF-310', 'J.G. Munoz-Cobos', 'PAPIN. A Fortran-IV Program to Calculate Cross Sections Probability...', 'Aug-81', 'ORNL/TM-7883', 'https://www.nndc.bnl.gov/endfdocs/ENDF-310.ORNL-TM-7883.pdf'),
  (246, 'ENDF-309', 'J.M. Kallfelz', 'Preliminary Analysis and Sensitivity Study of Phenix...', 'Sep-81', 'ORNL/TM-7505', ''),
  (245, 'ENDF-308', 'D.M. Hetrick, C.Y. Fu', 'A Calculation of Neutron and Gamma-Ray Production Cross Sections for Calcium from 8 to 20 MeV', 'Jun-81', 'ORNL/TM-7752', ''),
  (244, 'ENDF-307', 'D.K. Olsen', 'Measurement of Neutron Transmission Spectra Through 232-Th from 8 meV...', 'Apr-81', 'ORNL/TM-7661', ''),
  (243, 'ENDF-306', 'D.W. Muir, R.J. LaBauve', 'COVFILS: A 30-Group Covariance Library Based on ENDF/B-V', 'Mar-81', 'LA-8733-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-306.pdf'),
  (242, 'ENDF-305', 'J.D. Smith III, B.L. Broadhead', 'Multigroup Covariance Matrices for Fast Reactor Studies', 'Apr-81', 'ORNL/TM-7389', 'https://www.nndc.bnl.gov/endfdocs/ENDF-305,ENDF-295.pdf'),
  (241, 'ENDF-304', 'E.D. Arthur, P.G. Young', 'Evaluated Neutron-Induced Cross Sections for 54 and 56 Fe to 40 MeV', 'Dec-80', 'LA-8626-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-304.pdf'),
  (240, 'ENDF-303', 'D.M. Hetrick, C.Y. Fu', 'GLUCS: A Generalized Least-Squares Program for Updating Cross-Section Evaluations with Correlated Data Sets', 'Oct-80', 'ORNL/TM-7341', 'https://www.nndc.bnl.gov/endfdocs/ENDF-303.ORNL-TM-7341.pdf'),
  (239, 'ENDF-302', 'C.Y. Fu, F.G. Perey', 'Evaluation of Neutron and Gamma-Ray Production Cross Section for Natural Iron (ENDF/B-V MAT 1326)', 'Nov-80', 'ORNL/TM-7523', 'https://www.nndc.bnl.gov/endfdocs/ENDF-302.pdf'),
  (238, 'ENDF-301', 'A.D. Carlson, M.R. Bhat', 'ENDF/B-V Cross Section Measurement Standards', 'Oct-82', 'BNL-NCS-51619', 'https://www.nndc.bnl.gov/endfdocs/ENDF-301.pdf'),
  (237, 'ENDF-300 1984', 'M.R. Bhat', 'Standard Reference and Other Important Nuclear Data', 'May-84', 'BNL-NCS-51123 5/84', ''),
  (236, 'ENDF-300 1982', 'M.R. Bhat', 'Standard Reference and Other Important Nuclear Data', 'Feb-82', 'BNL-NCS-51123 2/82', ''),
  (235, 'ENDF-300 1981', 'M.R. Bhat', 'Standard Reference and Other Important Nuclear Data', 'Mar-81', 'BNL-NCS-51123 5/81', ''),
  (234, 'ENDF-300 1979', 'M.R. Bhat', 'Standard Reference and Other Important Nuclear Data by the CSEWG', 'Dec-79', 'BNL-NCS-51123', 'https://www.nndc.bnl.gov/endfdocs/ENDF-300-1979.pdf'),
  (233, 'ENDF-299', 'D.C. Larson', 'An Evaluation Cross Sections for Neutron-Induced Reactions in Sodium', 'Sep-80', 'ORNL-5662', 'https://www.nndc.bnl.gov/endfdocs/ENDF-299.pdf'),
  (232, 'ENDF-298', 'C.M. Perey, F.G. Perey', 'Evaluation of Resonance Parameters for Neutron Interaction with Iron Isotopes for Energies up to 400 keV', 'Sep-80', 'ORNL/TM-6405', 'https://www.nndc.bnl.gov/endfdocs/ENDF-298.pdf'),
  (231, 'ENDF-297', 'N.M. Larson, F.G. Perey, J.A. Harvey', 'User''s Guide for SAMMY: A Computer Model for Multilevel R-Matrix Fits to Neutron Data Using Bayes'' Equstions', 'Nov-80', 'ORNL/TM-7485', 'https://www.nndc.bnl.gov/endfdocs/ENDF-297.pdf'),
  (230, 'ENDF-296', 'R.W. Roussin, C.R. Weisbin, J.E. White, et al.', 'VITAMIN C: The CTR Processed Multigroup Cross Section Library for Neutronics Studies', 'Jul-80', 'ORNL/RSIC-37', 'https://www.nndc.bnl.gov/endfdocs/ENDF-296.pdf'),
  (229, 'ENDF-295', 'J.D. Smith III', 'Processing ENDF/B-V Uncertainty Data into Multigroup Covariance Matrices', 'Jun-80', 'ORNL/TM-7221', 'https://www.nndc.bnl.gov/endfdocs/ENDF-305,ENDF-295.pdf'),
  (228, 'ENDF-294', 'M. Divadeenam', 'Ni Elemental Neutron Induced Reaction Cross Section Evaluation', 'Mar-79', 'BNL-NCS-51346', 'https://www.nndc.bnl.gov/endfdocs/ENDF-294.pdf'),
  (227, 'ENDF-293', 'T. Burrows', 'ENDF/B-V Actinide Decay Data', '', '', ''),
  (226, 'ENDF-292', 'B.F. Rider', 'Compilation Efficient Products Yield', 'Sep-80', 'NEDO 12154-3(B)', ''),
  (225, 'ENDF-291 #2', 'J.D. Drischler', 'The COVERX Service Module of the FORSS System', 'Apr-80', 'ORNL/TM-7181', 'https://www.nndc.bnl.gov/endfdocs/ENDF-291-2.ORNL-TM-7181.pdf'),
  (224, 'ENDF-291 #1', 'J.L. Lucius, C.R. Weisbin, J.H. Marable, et al.', 'A Users Manual for the FORSS Sensitivity and Uncertainty Analysis Code System', 'Jan-84', 'ORNL-5316', 'https://www.nndc.bnl.gov/endfdocs/ENDF-291-1.ORNL-5316.pdf'),
  (223, 'ENDF-290', 'N.M. Larson, D.K. Olsen', 'Preliminary Study of Pseudorandom Binary Sequence Pulsing of ORELA', 'Mar-80', 'ORNL/TM-6632', 'https://www.nndc.bnl.gov/endfdocs/ENDF-290.pdf'),
  (222, 'ENDF-289', 'R. Gwin, R.R. Spencer, R.W. Ingle, et al.', 'Measurement of the Average Number of Prompt Neutrons Emitted per Fissionof 235U Relative to 252Cf ...', 'Jan-80', 'ORNL/TM-7148', 'https://www.nndc.bnl.gov/endfdocs/ENDF-289.pdf'),
  (221, 'ENDF-288', 'R.J. Barrett, W.E. Ford III, Y. Gohar, et al.', 'Comparison of Photon-Production Processing Codes LAPHNGAS, MACK-IV, and NJOY', 'Nov-79', 'LA-8100-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-288.pdf'),
  (220, 'ENDF-287', 'W.E. Ford III, C.C. Webster, B.R. Diggs, et al.', 'FCXSEC:Multigroup Cross-Section Libraries for Nuclear Fuel CycleShielding Calculations', 'May-80', 'ORNL/TM-7038', 'https://www.nndc.bnl.gov/endfdocs/ENDF-287.pdf'),
  (219, 'ENDF-286', 'A. Prince, T.W. Burrows', 'Evaluation of Natural Chromium Neutron Cross Sections for ENDF/B-V', 'Feb-79', 'BNL-NCS-51152', 'https://www.nndc.bnl.gov/endfdocs/ENDF-286.pdf'),
  (218, 'ENDF-285', 'R.R. Spencer, R. Gwin, R. Ingle, H. Weaver', 'Interim Report on the ORNL Absolute Measurements of nu p for 252Cf', 'Sep-79', 'ORNL/TM-6805', 'https://www.nndc.bnl.gov/endfdocs/ENDF-285.pdf'),
  (217, 'ENDF-284', 'G.L. Morgan, G.T. Chapman', 'The O(n,x gamma) Reaction Cross Section for Incident Neutron EnergiesBetween 6.5 and 20.0 MeV', 'Sep-79', 'ORNL-5575', 'https://www.nndc.bnl.gov/endfdocs/ENDF-284.pdf'),
  (216, 'ENDF-283', 'P.G. Young, L. Stewart', 'Evaluated Data for n+Berylium 9 Reactions', 'Jul-79', 'LA-7932-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-283.pdf'),
  (215, 'ENDF-282', 'G.L. Morgan', 'The Th(n,x gamma) Reaction Cross Section for Incident Neutron EnergiesBetween 0.3 and 20.0 Mev', 'Aug-79', 'ORNL/TM-6758', 'https://www.nndc.bnl.gov/endfdocs/ENDF-282.pdf'),
  (214, 'ENDF-281', 'D.K. Olsen, G.L. Morgan, J.W. McConnell', 'Measurement of 238-U(n,n''gamma) and Li-7(n,n''gamma) Gamma-Ray Production Cross Sections', 'May-79', 'ORNL/TM-6832', 'https://www.nndc.bnl.gov/endfdocs/ENDF-281.pdf'),
  (213, 'ENDF-280', 'D.M. Hetrick, D.C. Larson, C.Y. Fu', 'Status of ENDF/B-V Neutron Emission Spectra Induced by 14 MeV Neutrons', 'Apr-79', 'ORNL/TM-6637', 'https://www.nndc.bnl.gov/endfdocs/ENDF-280.pdf'),
  (212, 'ENDF-279', 'A. Prince', 'ENDF/B-V Neutron Cross Section Evaluation for the Krypton Isotopes', 'Jan-79', 'BNL-NCS-51028', 'https://www.nndc.bnl.gov/endfdocs/ENDF-279.pdf'),
  (211, 'ENDF-278', 'L. Stewart', 'Summary of Fission Spectrum Workshop Held at NNCSC', 'Oct-78', 'LA-7739-C', 'https://www.nndc.bnl.gov/endfdocs/ENDF-278.pdf'),
  (210, 'ENDF-277', 'F.C. Difilippo, R.B. Perez, G. deSaussure, et al.', 'The U-238 Neutron Induced Fission Cross Section for Incident NeutronEnergies Between 5 eV and 3.5 MeV', 'Feb-79', 'ORNL/TM-6788', 'https://www.nndc.bnl.gov/endfdocs/ENDF-277.pdf'),
  (209, 'ENDF-276', 'C.R. Weisbin', 'Specifications for Adjusted Cross Sections and Covariance Libraries based...', 'Feb-79', 'ORNL-5517', ''),
  (208, 'ENDF-275', 'J.L. Lucius, E.M. Oblow, G.W. Cunningham,III', 'A Users Guide for the JULIET Module of the FORSS Sensitivity andUncertainty Analysis Code System', 'Feb-79', 'ORNL/TM-6594', 'https://www.nndc.bnl.gov/endfdocs/ENDF-275.pdf'),
  (207, 'ENDF-274', 'C.R. Weisbin, R.W. Roussin, J.J. Wagschal, et al.', 'VITAMIN-E: An ENDF/B-V Multigroup Cross Section Library for LMFBR Core and Shield, LWR Shield,...', 'Dec-78', 'ORNL-5505', 'https://www.nndc.bnl.gov/endfdocs/ENDF-274.pdf'),
  (206, 'ENDF-273', 'G.L. Morgan', 'Cross Sections for the Cu(n,xn) and Cu(n,x gamma) Reactions Between 1 and 20 Mev', 'Feb-79', 'ORNL-5499', 'https://www.nndc.bnl.gov/endfdocs/ENDF-273.pdf'),
  (205, 'ENDF-272', 'R.E. MacFarlane, R.J. Barrett, D.W. Muir, R.M. Boicourt', 'The NJOY Nuclear Data Processing System: Users Manual', 'Dec-78', 'LA-7584-M', 'https://www.nndc.bnl.gov/endfdocs/ENDF-272.pdf'),
  (204, 'ENDF-271', 'F.M. Mann', 'HEDL Evaluation of Thorium Cycle Cross Sections for ENDF/B-V', 'Nov-78', 'HEDL-TME-78-100', ''),
  (203, 'ENDF-270', 'P.F. Rose, S. Pearlstein, O. Ozer', 'Symposium Proceedings: Nuclear Data Problems for Thermal ReactorApplications', 'Jun-79', 'BNL-NCS-25047', 'https://www.nndc.bnl.gov/endfdocs/ENDF-270.pdf'),
  (202, 'ENDF-269', 'J.U. Koppel, D.H. Houston', 'Reference Manual for ENDF Thermal Neutron Scattering Data', 'Jul-78', 'GA-8774 Revised', 'https://www.nndc.bnl.gov/endfdocs/ENDF-269.pdf'),
  (201, 'ENDF-268', 'M.R. Bhat', 'Evaluation of Th-232 for ENDF/B-V', 'Feb-81', 'BNL-NCS-51360', 'https://www.nndc.bnl.gov/endfdocs/ENDF-268.pdf'),
  (200, 'ENDF-267', 'C.Y. Fu', 'Evaluation for Th-233(n,n'')(n,2n) and (n,3n) Cross Section', 'May-78', 'ORNL/TM-6316', ''),
  (199, 'ENDF-266', 'Y.D. Harker, J.W. Rogers, D.A. Millsap', 'Fission Product and Reactor Dosimetry Studies at Coupled Fast Reactivity Measurements Facility', 'Mar-78', 'TREE-1259', 'https://www.nndc.bnl.gov/endfdocs/ENDF-266.pdf'),
  (198, 'ENDF-265', 'C.R. Weisbin, J.H. Marable, J. Hardy Jr., R.D. McKnight', 'Sensitivity Coefficient Compilation for CSEWG Data Testing Benchmarks', 'Aug-78', 'BNL-NCS-24853', ''),
  (197, 'ENDF-264', 'R. Gwin, R.R. Spencer, R.W. Ingle, et al.', 'Measurements of the Average Number of Prompt Neutrons Emitted per Fission of 239Pu and 235U', 'May-78', 'ORNL/TM-6246', 'https://www.nndc.bnl.gov/endfdocs/ENDF-264.pdf'),
  (196, 'ENDF-263', 'M.L. Williams, C.R. Weisbin', 'Sensitivity and Uncertainity Analysis for Functionals of the Time-Dependent Nuclide Density Field', 'Apr-78', 'ORNL-5393', 'https://www.nndc.bnl.gov/endfdocs/ENDF-263.pdf'),
  (195, 'ENDF-262', 'R. Gwin', 'Review and Combination of Experimental Results for Neutron-Emission per Fission of 232Th', 'May-78', 'ORNL/TM-6245', 'https://www.nndc.bnl.gov/endfdocs/ENDF-262.pdf'),
  (194, 'ENDF-261', 'G. De Saussure, D.K. Olsen, R.B. Perey', 'SIOB: A Fortran Code for Least Squares Shape Fitting Several Neutron Transmission Measurements Using ...', 'May-78', 'ORNL/TM-6286', 'https://www.nndc.bnl.gov/endfdocs/ENDF-261.pdf'),
  (193, 'ENDF-260', 'G. De Saussure, R.L. Macklin', 'Evaluation of the Th-232 Neutron Capture Cross Section above 3 keV', 'Feb-78', 'ORNL/TM-6161', 'https://www.nndc.bnl.gov/endfdocs/ENDF-260.pdf'),
  (192, 'ENDF-259', 'F.G. Perey', 'Contributions to Few-Channel Spectrum Unfolding', 'Feb-78', 'ORNL/TM-6267', 'https://www.nndc.bnl.gov/endfdocs/ENDF-259.pdf'),
  (191, 'ENDF-258', 'R.E. Maerker, F.J. Muckenthaler, C.E. Clifford', 'SB4. Measurements and Calculations of the ORNL CRBR Upper Axial Shield Experiment', 'Jun-77', 'ORNL-5259', 'https://www.nndc.bnl.gov/endfdocs/ENDF-258.pdf'),
  (190, 'ENDF-257', 'G. De Saussure, D.K. Olsen, R.B. Perey, F.C. Difilippo', 'Evaluation of the U-238 Neutron Cross Sections for Incident Neutron Energies up to 4 Kev', 'Jan-78', 'ORNL/TM-6152', 'https://www.nndc.bnl.gov/endfdocs/ENDF-257.pdf'),
  (189, 'ENDF-256', 'J.D. Drischler, J.H. Marable, C.R. Weisbin', 'COVERT and CAVALIER: Two Computer Codes for Estimating Uncertainties of Calculated Neutronics Parameters ...', 'Aug-78', 'ORNL/TM-6078', 'https://www.nndc.bnl.gov/endfdocs/ENDF-256.pdf'),
  (188, 'ENDF-255', 'D.K. Olsen, G. deSaussure, R.B. Perey, et al.', '150-m Measurement of 0.880- to 100.0-keV Neutron Transmissions ThroughFour Samples of 238U', 'Oct-77', 'ORNL/TM-5915', 'https://www.nndc.bnl.gov/endfdocs/ENDF-255.pdf'),
  (187, 'ENDF-254', 'F.G. Perey', 'Least-Squares Dosimetry Unfolding: the Program STAY''SL', 'Oct-77', 'ORNL/TM-6062', 'https://www.nndc.bnl.gov/endfdocs/ENDF-254.pdf'),
  (186, 'ENDF-253', 'E.T. Tomlinson, J.L. Lucius, J.D. Drischler', 'A Compendium of Energy-Dependent Sensitivity Profiles for TRX-2 Thermal Lattice', 'Mar-78', 'ORNL-5336', 'https://www.nndc.bnl.gov/endfdocs/ENDF-253.pdf'),
  (185, 'ENDF-252', 'E.T. Tomlinson, D. deSaussure, C.R. Weisbin', 'Sensitivity Analysis of TRX-2 Lattice Parameters with Emphasis on Epithermal 238-U Capture', 'Mar-77', 'EPRI-NP-346', 'https://www.nndc.bnl.gov/endfdocs/ENDF-252.pdf'),
  (184, 'ENDF-251', 'F.M. Mann', 'HEDL Evaluation of Actinide Cross Section for ENDF/B-V', 'Jun-77', 'HEDL-TME-77-54', ''),
  (183, 'ENDF-250', 'J.H. Marable, J.D. Drischler, C.R. Weisbin', 'SENDIN and SENTINEL: Two Computer Codes to Assess the Effects of Nuclear Data Changes', 'Jul-77', 'ORNL/TM-5946', 'https://www.nndc.bnl.gov/endfdocs/ENDF-250.pdf'),
  (182, 'ENDF-249', 'F.G. Perey', 'Data Covariance Files for ENDF/B-V', 'Jul-77', 'ORNL/TM-5938', 'https://www.nndc.bnl.gov/endfdocs/ENDF-249.pdf'),
  (181, 'ENDF-248', 'M.R. Bhat', 'Evaluation of 235-U Neutron Cross Section and Gamma Ray Production Data for ENDF/B-V', 'Mar-80', 'BNL-NCS-51184', 'https://www.nndc.bnl.gov/endfdocs/ENDF-248.pdf'),
  (180, 'ENDF-247', 'D.G. Madland, L. Stewart', 'Light Ternary Fission Products: Probabilities and Charge Distributions', 'Apr-77', 'LA-6783-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-247.pdf'),
  (179, 'ENDF-246', 'A. Prince', 'Evaluation of Chromium Neutron and Gamma Production Cross Sections for ENDF/IV', 'Aug-76', 'BNL-NCS-50593', 'https://www.nndc.bnl.gov/endfdocs/ENDF-246.pdf'),
  (178, 'ENDF-245', 'F.M. Mann', 'HAUSER*4: A Computer Code to Calculate Nuclear Cross Sections', 'Sep-76', 'HEDL-TME-76-80', ''),
  (177, 'ENDF-244', 'G.M. Hale, L. Stewart, P.G. Young', 'Light Element Standard Cross Standards for ENDF/B-IV', 'Oct-76', 'LA-6518-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-244.pdf'),
  (176, 'ENDF-243 Vol.II', 'P.F. Rose, T.W. Burrows', 'ENDF/B Fission Product Decay Data', 'Aug-76', 'BNL-NCS-50545 Vol.II', 'https://www.nndc.bnl.gov/endfdocs/ENDF-243-Vol2.pdf'),
  (175, 'ENDF-243 Vol.I', 'P.F. Rose, T.W. Burrows', 'ENDF/B Fission Product Decay Data', 'Aug-76', 'BNL-NCS-50545 Vol.I', 'https://www.nndc.bnl.gov/endfdocs/ENDF-243-Vol1.pdf'),
  (174, 'ENDF-242', 'M. Stamatelatos, T.R. England', 'Beta-Energy Averaging and Beta Spectra', 'Aug-76', 'LA-6445-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-242.pdf'),
  (173, 'ENDF-241', 'D.G. Madland, T.R. England', 'Distribution of Independent Fission-Product Yields to Isomeric States', 'Nov-76', 'LA-6595-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-241.pdf'),
  (172, 'ENDF-240', 'D.G. Madland, T.R. England', 'The Influence of Pairing on the Distribution of Independent Yield Strengths in Neutron-induced Fission', 'Jul-76', 'LA-6430-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-240.pdf'),
  (171, 'ENDF-239', 'H. Henryson II', 'MC2-2: A Code to Calculate Fast Neutron Spectra and Multigroup CrossSections', 'Jun-76', 'ANL-8144', 'https://www.nndc.bnl.gov/endfdocs/ENDF-239.pdf'),
  (170, 'ENDF-238', 'R.A. Grimesey', 'ETOP 14: A Fortran Code to Process ENDF/B Data into the 68-Group PHROG...', 'Jul-76', 'ANCR-1322', ''),
  (169, 'ENDF-237', 'C.R. Weisbin, P.D. Soran, R.E. MacFarlane, et al.', 'MINX: A Multigroup Interpretation of Nuclear X-Sections from ENDF/B', 'Sep-76', 'LA-6486-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-237.pdf'),
  (168, 'ENDF-236', 'C.R. Weisbin', 'Application of FORSS Sensitivity and Uncertainty Methodology to Fast', 'Dec-76', 'ORNL/TM-5563', ''),
  (167, 'ENDF-235', 'J.D. Drischler, C.R. Weisbin', 'Compilation of Multigroup Cross-Section Covariance Matrices for Several Important Reactor Materials', 'Oct-77', 'ORNL-5318', ''),
  (166, 'ENDF-234', 'J.H. Marable, J.L. Lucius, C.R. Weibin', 'Compilation of Sensitivity Profiles for Several CSEWG Fast Reactor Benchmarks', 'Mar-77', 'ORNL-5262', 'https://www.nndc.bnl.gov/endfdocs/ENDF-234.pdf'),
  (165, 'ENDF-233', 'R.W. Peelle', 'An Evaluation for ENDF/B-IV of the Neutron Cross Sections for U-235 from 82 eV to 25 keV', 'Jun-76', 'ORNL-4955', 'https://www.nndc.bnl.gov/endfdocs/ENDF-233.pdf'),
  (164, 'ENDF-232', 'A. Prince', 'Evaluation of Neutron Cross Sections For the Krypton Isotopes', 'Aug-74', 'BNL-NCS-50503', 'https://www.nndc.bnl.gov/endfdocs/ENDF-232.pdf'),
  (163, 'ENDF-231', 'Void See ENDF-265', '', '', '', ''),
  (162, 'ENDF-230 Vol.II', 'E.M. Bohn, R. Maerker, B.A. Magurno, et al.', 'Benchmark Testing of ENDF/B-IV', 'Mar-76', 'BNL-NCS-21118 Vol.II', 'https://www.nndc.bnl.gov/endfdocs/ENDF-230-Vol2.pdf'),
  (161, 'ENDF-230 Vol.I', 'E.M. Bohn, R. Maerker, B.A. Magurno, et al.', 'Benchmark Testing of ENDF/B-IV', 'Mar-76', 'BNL-NCS-21118 Vol.I', 'https://www.nndc.bnl.gov/endfdocs/ENDF-230-Vol1.pdf'),
  (160, 'ENDF-229', 'S.F. Mughabghab, T.J. Krieger', 'Neutron Cross Sections of 59Co Below 100 keV', 'Apr-75', 'BNL-NCS-50468', 'https://www.nndc.bnl.gov/endfdocs/ENDF-229.pdf'),
  (159, 'ENDF-228', 'R.E. Maerker', 'SB3. Experiment on Secondary Gamma-Ray Production Cross Sections Averaged ...', 'Jan-76', 'ORNL/TM-5204', 'https://www.nndc.bnl.gov/endfdocs/ENDF-228.pdf'),
  (158, 'ENDF-227', 'R.E. Maerker', 'SB2. Experiment on Secondary Gamma-Ray Production Cross Sections Arisingfrom Thermal-Neutron Capture ...', 'Jan-76', 'ORNL-TM-5203', 'https://www.nndc.bnl.gov/endfdocs/ENDF-227.pdf'),
  (157, 'ENDF-226', 'R.E. Maerker', 'Subject: Benchmark', '', 'ORNL/TM-5202', ''),
  (156, 'ENDF-225', 'B.A. Magurno', 'ENDF/B-IV Cross Section Measurement Standards', 'Aug-75', 'BNL-NCS-50464', 'https://www.nndc.bnl.gov/endfdocs/ENDF-225.pdf'),
  (155, 'ENDF-224', 'C.R. Weisbin', 'Specification for Pseudo-Composition-Independent Fine-Group and...', 'Dec-75', 'ORNL/TM-5142', ''),
  (154, 'ENDF-223', 'T.R. England, R.E. Schenter', 'ENDF/B-IV Fission-Product Files: Summary of Major Nuclide Data', 'Oct-75', 'LA-6116-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-223.pdf'),
  (153, 'ENDF-222', 'G.L. Morgan', 'Cr(n,x gamma)Reaction Cross Section for Incident Neutron Energies Between ...', 'Jan-76', 'ORNL/TM-5098', ''),
  (152, 'ENDF-221', 'E. Newman, G.L. Morgan', 'V(n,x gamma) Reaction Cross Section for Incident Neutron Energies Between 0.2 and 20.0 MeV', 'Apr-76', 'ORNL/TM-5299', 'https://www.nndc.bnl.gov/endfdocs/ENDF-221.pdf'),
  (151, 'ENDF-220', 'G.L. Morgan, E. Newman', 'The Mo(n,x gamma) Reaction Cross Section for Incident Neutron Energies Between 0.2 and 20.0 MeV', 'Dec-75', 'ORNL-TM-5097', ''),
  (150, 'ENDF-219', 'J.K. Dickens, G.L. Morgan, E. Newman', 'The Nb(n,x gamma) Reaction Cross Section for Incident Neutron Energies Between 0.65 and 20.0 MeV', 'Sep-75', 'ORNL-TM-4972', 'https://www.nndc.bnl.gov/endfdocs/ENDF-219.pdf'),
  (149, 'ENDF-218', 'C.R. Weisbin, E.M. Oblow, J. Ching, et al.', 'Cross Section and Method Uncertainties:the Applicati on of SensitivityAnalysis ...', 'Aug-75', 'ORNL-TM-4847', 'https://www.nndc.bnl.gov/endfdocs/ENDF-218.pdf'),
  (148, 'ENDF-217', 'S. Pearlstein', 'Seminar on 238-U Resonance Capture', 'Mar-75', 'BNL-NCS-50451', 'https://www.nndc.bnl.gov/endfdocs/ENDF-217.pdf'),
  (147, 'ENDF-216', 'B.A. Magurno', 'ENDF/B-IV Dosimetry File', 'Apr-75', 'BNL-NCS-50446', 'https://www.nndc.bnl.gov/endfdocs/ENDF-216.pdf'),
  (146, 'ENDF-215', 'S.F. Mughabghab, A. Prince, M.D. Goldberg, et al.', 'Evaluated Neutron Cross Sections of Au-197', 'Oct-74', 'BNL-50439', 'https://www.nndc.bnl.gov/endfdocs/ENDF-215.pdf'),
  (145, 'ENDF-214', 'H. Takahashi', 'Evaluation of the Neutron Cross Sections for Eu-152 and Eu-154', 'Nov-74', 'BNL-19456', 'https://www.nndc.bnl.gov/endfdocs/ENDF-214.pdf'),
  (144, 'ENDF-213', 'H.Takahashi', 'Evaluation of the Neutron and Gamma-Ray Production Cross Sections of Eu-151 and Eu-153', 'Nov-74', 'BNL-19455', 'https://www.nndc.bnl.gov/endfdocs/ENDF-213.pdf'),
  (143, 'ENDF-212', 'M.R. Bhat, B.A. Magurno, S. Pearlstein, F.M. Scheffel', 'Nuclear Data for CTR Related Projects', 'Oct-74', 'BNL-19344', 'https://www.nndc.bnl.gov/endfdocs/ENDF-212.pdf'),
  (142, 'ENDF-211', 'Void-Not Used', '', '', '', ''),
  (141, 'ENDF-210', 'C.W. Reich, R.G. Helmer, M.H. Putnam', 'Radioactive-Nuclide Decay Data for ENDF/B', 'Aug-74', 'ANCR-1157', 'https://www.nndc.bnl.gov/endfdocs/ENDF-210.pdf'),
  (140, 'ENDF-209', 'Void See ENDF-246', '', '', '', ''),
  (139, 'ENDF-208', 'H. Takahashi', 'Evaluation of the Neutron and Gamma-Ray Production Cross Sections for 55Mn', 'Nov-74', 'BNL-50442', 'https://www.nndc.bnl.gov/endfdocs/ENDF-208.pdf'),
  (138, 'ENDF-207', 'M.R. Bhat', 'Neutron and Gamma-Ray Production Cross Sections for Nickel', 'Oct-74', 'BNL-50435', 'https://www.nndc.bnl.gov/endfdocs/ENDF-207.pdf'),
  (137, 'ENDF-206', 'W.E. Kinney, F.G. Perey', 'Pb-206, Pb-207, and Pb-208 Neutron Elastic and Inelastic Scattering Cross From 5.50 To 8.50 MeV', 'Jun-74', 'ORNL-4909', 'https://www.nndc.bnl.gov/endfdocs/ENDF-206.pdf'),
  (136, 'ENDF-205', 'F.G. Perey', 'Nitrogen Neutron Elastic and Inelastic Scattering Cross Sections From 4.34...', 'Mar-74', 'ORNL-4905', ''),
  (135, 'ENDF-204', 'W.E. Kinney, F.G. Perey', 'Cu-63 and Cu-65 Neutron Elastic and Inelastic Scattering Cross Sections From 5.50 To 8.50 MeV', 'Mar-74', 'ORNL-4908', 'https://www.nndc.bnl.gov/endfdocs/ENDF-204.pdf'),
  (134, 'ENDF-203', 'W.E. Kinney, F.G. Perey', 'Fe-54 Neutron Elastic and Inelastic Scattering Cross Sections From 5.50 To 8.50 MeV', 'Mar-74', 'ORNL-4907', 'https://www.nndc.bnl.gov/endfdocs/ENDF-203.pdf'),
  (133, 'ENDF-202 1991', 'R. McKnight', 'Cross Sections Evaluation Working Group Benchmark Specification', 'Sep-91', 'BNL-19302 Upd. 9/91', ''),
  (132, 'ENDF-202 1983 Vol.2 Suppl.', 'P.F. Rose', 'Cross Section Evaluation Working Group Benchmark Specifications', 'Sep-86', 'BNL-19302 Vol.2 Suppl.', ''),
  (131, 'ENDF-202 1983 Vol.2', 'P.F. Rose', 'Cross Sections Evaluation Working Group Benchmark Specifications', 'Dec-83', 'BNL-19302 Vol.2', ''),
  (130, 'ENDF-202 1982', 'H. Alter', 'Cross Sections Evaluation Working Group Benchmark Specification', 'Sep-82', 'BNL-19302 Upd. 9/82', ''),
  (129, 'ENDF-202 1981-2', 'H. Alter', 'Cross Sections Evaluation Working Group Benchmark Specification', 'Nov-81', 'BNL-19302 Upd.11/81', ''),
  (128, 'ENDF-202 1981-1', 'H. Alter', 'Cross Sections Evaluation Working Group Benchmark Specification', 'May-81', 'BNL-19302 Upd. 5/81', ''),
  (127, 'ENDF-202 1978-2', 'H. Alter', 'Cross Sections Evaluation Working Group Benchmark Specification', 'Oct-78', 'BNL-19302 Upd. 10/78', ''),
  (126, 'ENDF-202 1978-1', 'H. Alter', 'Cross Sections Evaluation Working Group Benchmark Specification', 'Feb-78', 'BNL-19302 Upd. 2/78', ''),
  (125, 'ENDF-202 1976', 'H. Alter', 'Cross Sections Evaluation Working Group Benchmark Specification', 'Oct-76', 'BNL-19302 Upd. 10/76', ''),
  (124, 'ENDF-202 1975', 'H. Alter', 'Cross Sections Evaluation Working Group Benchmark Specification', 'May-75', 'BNL-19302 Upd. 5/75', ''),
  (123, 'ENDF-202 1974 Vol.2', 'H. Alter', 'Cross Sections Evaluation Working Group Benchmark Specification', 'Nov-74', 'BNL-19302 Vol. 2', 'https://www.nndc.bnl.gov/endfdocs/ENDF-202-Vol2.pdf'),
  (122, 'ENDF-202 1974 Vol.1', 'H. Alter', 'Cross Sections Evaluation Working Group Benchmark Specification', 'Nov-74', 'BNL-19302', 'https://www.nndc.bnl.gov/endfdocs/ENDF-202-Vol1.pdf'),
  (121, 'ENDF-201 4th Ed. Suppl. 1', 'V. McLane', 'ENDF/B-VI Summary Documentation Supplement 1, ENDF/HE-VI Summary Documentation', 'Dec-96', 'BNL-NCS-17541 4th Ed. Suppl.1', 'https://www.nndc.bnl.gov/endfdocs/ENDF-201-4th-SUPP.pdf'),
  (120, 'ENDF-201 4th Ed.', 'P.F. Rose', 'ENDF/B-VI Summary Documentation', 'Oct-91', 'BNL-NCS-17541 4th Ed.', ''),
  (119, 'ENDF-201 1985', 'B.A. Magurno. P.G. Young', 'ENDF/B-V.2 Summary Documentation', 'Jan-85', 'BNL-NCS-17541 3rd Ed. Suppl.1', 'https://www.nndc.bnl.gov/endfdocs/ENDF-201-1985.pdf'),
  (118, 'ENDF-201 1979', 'R.R. Kinsey', 'ENDF/B Summary Documentation', 'Jul-79', 'BNL-NCS-17541 3rd Ed.', 'https://www.nndc.bnl.gov/endfdocs/ENDF-201-1979.pdf'),
  (117, 'ENDF-201 1975', 'D.I. Garber', 'ENDF/B Summary Documentation', 'Oct-75', 'BNL-NCS-17541 2nd Ed.', ''),
  (116, 'ENDF-201 1973', 'O. Ozer, D. Garber', 'ENDF/B Summary Documentation', 'May-73', 'BNL-NCS-17541 1st Ed.', 'https://www.nndc.bnl.gov/endfdocs/ENDF-201-1973.pdf'),
  (115, 'ENDF-200 2nd Edition', 'D.I. Garber, C. Brewster', 'ENDF/B Cross Sections', 'Oct-75', 'BNL-17100 2nd Ed.', ''),
  (114, 'ENDF-200', 'D.E. Cullen, P.J. Hlavac', 'ENDF/B Cross Sections', 'Nov-72', 'BNL-17100', ''),
  (113, 'ENDF-199', 'B. Hutchins', 'Subject: Pu-239', '', '', ''),
  (112, 'ENDF-198', 'W.E. Kinney, F.G. Perey', 'Natural Chromium and Cr-52 Neutron Elastic and Inelastic Scattering Cross Sections from 4.07 to 8.56 MeV', 'Jan-74', 'ORNL-4806', 'https://www.nndc.bnl.gov/endfdocs/ENDF-198.pdf'),
  (111, 'ENDF-197', 'W.E. Kinney, F.G. Perey', 'Natural Nickel and Ni-60 Neutron Elastic and Inelastic Scattering Cross Sections from 4.07 to 8.56 MeV', 'Jan-74', 'ORNL-4807', 'https://www.nndc.bnl.gov/endfdocs/ENDF-197.pdf'),
  (110, 'ENDF-196', 'D.R. Finch', 'Standard Thermal Energy Group Structure for Generation of Thermal Group Constants from ENDF/B Data', 'Mar-74', 'DP-1346', 'https://www.nndc.bnl.gov/endfdocs/ENDF-196.pdf'),
  (109, 'ENDF-195', 'F. Schmittroth', 'Neutron Capture Calculations for En=3D100 keV to 4 MeV', 'Nov-73', 'HEDL-TME-73-79', ''),
  (108, 'ENDF-194', 'F. Schmittroth, R.E. Schenter', 'Fast Neutron Capture Cross Section for Fission Product Isotopes', 'Aug-73', 'HEDL-TME-73-63', 'https://www.nndc.bnl.gov/endfdocs/ENDF-194.pdf'),
  (107, 'ENDF-193', 'Void-Not Used', '', '', '', ''),
  (106, 'ENDF-192', 'C.R. Weisbin', 'Specification of a Generally Useful Multigroup Structure for NeutronTranspor', 'May-73', 'LA-5277-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-192.pdf'),
  (105, 'ENDF-191', 'R.Q. Wright', 'ADLER-III: A Program to Calculate Cross Sections from Adler-Adler Resonance Parameters', 'Jun-73', 'ORNL-TM-4257', 'https://www.nndc.bnl.gov/endfdocs/ENDF-191.pdf'),
  (104, 'ENDF-190', 'A. Prince, M.K. Drake, P. Hlavac', 'An Analysis of the Pu-239 Neutron Cross Sections from 20 keV to 20 MeV', 'Apr-73', 'BNL-50388', 'https://www.nndc.bnl.gov/endfdocs/ENDF-190.pdf'),
  (103, 'ENDF-189', 'R.E. Maerker', 'SDT12. The ORNL Benchmark Experiment for Neutron Transport Through Sodium', 'Sep-74', 'ORNL-TM-4223', 'https://www.nndc.bnl.gov/endfdocs/ENDF-189.pdf'),
  (102, 'ENDF-188', 'R.E. Maerker', 'SDT11. The ORNL Benchmark Experiment for Neutron Transport Through Iron and Stainless Steel, Part 1', 'Sep-74', 'ORNL-TM-4222', 'https://www.nndc.bnl.gov/endfdocs/ENDF-188.pdf'),
  (101, 'ENDF-187', 'M.R. Bhat', 'Multi-Level Effects in Reactor Calculations and the Probability TableMethod', 'Apr-73', 'BNL-50387', 'https://www.nndc.bnl.gov/endfdocs/ENDF-187.pdf'),
  (100, 'ENDF-186', 'M.R. Bhat, M.D. Goldberg, R.R. Kinsey, et al.', 'Neutron and Gamma Ray Production Cross Sections for Silicon', 'Mar-73', 'BNL-50379', 'https://www.nndc.bnl.gov/endfdocs/ENDF-186.pdf'),
  (99, 'ENDF-185', 'M.R. Bhat, S.F. Mughabghab', 'Evaluated Neutron Cross Sections for the Stable Isotopes of Xenon', 'Feb-73', 'BNL-50374', 'https://www.nndc.bnl.gov/endfdocs/ENDF-185.pdf'),
  (98, 'ENDF-184', 'R.Q. Wright', 'A Comparison of the Group Constants Generated by the ENDF/B Processing...', 'Apr-73', 'ORNL/TM-4041', ''),
  (97, 'ENDF-183', 'H. Alter', 'Report to the Cross Section Evaluation Working Group GEDANKEN Calculations', 'Nov-72', 'BNL-17510', ''),
  (96, 'ENDF-182', 'D.J. Dudziak, G.E. Bosler', 'LAPHAN: A Code to Compute the P0 to P4 Multigroup Photon-Production Matrices', 'Jan-73', 'LA-4963', 'https://www.nndc.bnl.gov/endfdocs/ENDF-182.pdf'),
  (95, 'ENDF-181', 'P.F. Rose, H. Alter, R.K. Paschall, A.W. Thiele', 'SDT9. CSEWG Shielding Benchmark Specifications Neutron AttenuationMeasurements in a Mockup of the FFTF Radial Shield', 'Jan-73', 'AI-AEC-13048', 'https://www.nndc.bnl.gov/endfdocs/ENDF-181.pdf'),
  (94, 'ENDF-180', 'W.E. Ford III', 'The Testing of Photon Production Data from ENDF/B-III Material 1135(Al)', 'Jan-73', 'ORNL-TM-4032', ''),
  (93, 'ENDF-179', 'M.K. Drake', 'ENDF/B-III Cross Section Measurement Standards', 'Jul-72', 'BNL-17188', 'https://www.nndc.bnl.gov/endfdocs/ENDF-179.pdf'),
  (92, 'ENDF-178', 'F.G. Perey', 'A Test of Neutron Total Cross Section Evaluations from 0.2 to 20 MeV for ...', 'Dec-72', 'ORNL-4823', ''),
  (91, 'ENDF-177', 'R.E. Maerker', 'SDT7. Experiment on Secondary Gamma-ray Production Cross Sections Arising ...', 'Oct-72', 'ORNL/TM-3974', 'https://www.nndc.bnl.gov/endfdocs/ENDF-177.pdf'),
  (90, 'ENDF-176', 'R.E. Maerker', 'SDT6. Experiment on Secondary Gamma-Ray Production Cross Sections Arising from Thermal-Neutron Capture in Iron, Stainless Steel, Nitrogen, and Sodium', 'Oct-72', 'ORNL/TM-3957', 'https://www.nndc.bnl.gov/endfdocs/ENDF-176.pdf'),
  (89, 'ENDF-175', 'P.G. Young', 'A Preliminary Evaluation of the Neutron and Photon-Production Cross Sections for Aluminum', 'Dec-72', 'LA-4726', 'https://www.nndc.bnl.gov/endfdocs/ENDF-175.pdf'),
  (88, 'ENDF-174', 'D.G. Foster', 'A Preliminary Evaluation of the Neutron and Photon Production Cross Sections of Oxygen', 'Aug-72', 'LA-4780', 'https://www.nndc.bnl.gov/endfdocs/ENDF-174.pdf'),
  (87, 'ENDF-173', 'P.G. Young', 'Evaluation of the Neutron and Gamma Ray Production Cross Sections for Nitrogen', 'Sep-72', 'LA-4725', 'https://www.nndc.bnl.gov/endfdocs/ENDF-173.pdf'),
  (86, 'ENDF-172', 'W.E. Ford III', 'Comparison of (n th,gamma) Yields from the Current ENDF/B-III Data with Published Data', 'Aug-72', 'ORNL-TM-3910', 'https://www.nndc.bnl.gov/endfdocs/ENDF-172.pdf'),
  (85, 'ENDF-171', 'F. Schmittroth', 'Neutron Resonance Spacings for Spherical Nuclei', 'Jan-73', 'HEDL-TME-73-30', 'https://www.nndc.bnl.gov/endfdocs/ENDF-171.pdf'),
  (84, 'ENDF-170', 'R.E. Maerker', 'SDT5. Stainless-Steel Broomstick Experiment', 'Jul-72', 'ORNL/TM-3871', 'https://www.nndc.bnl.gov/endfdocs/ENDF-170.pdf'),
  (83, 'ENDF-169', 'R.E. Maerker', 'SDT4. Sodium Broomstick Experiment', 'Jul-72', 'ORNL/TM-3870', 'https://www.nndc.bnl.gov/endfdocs/ENDF-169.pdf'),
  (82, 'ENDF-168', 'R.E. Maerker', 'SDT3. Nitrogen Broomstick Experiment', 'Jul-72', 'ORNL/TM-3869', 'https://www.nndc.bnl.gov/endfdocs/ENDF-168.pdf'),
  (81, 'ENDF-167', 'R.E. Maerker', 'SDT2. Oxygen Broomstick Experiment', 'Jul-72', 'ORNL/TM-3868', 'https://www.nndc.bnl.gov/endfdocs/ENDF-167.pdf'),
  (80, 'ENDF-166', 'R.E. Maerker', 'SDT1. Iron Broomstick Experiment', 'Jul-72', 'ORNL/TM-3867', 'https://www.nndc.bnl.gov/endfdocs/ENDF-166.pdf'),
  (79, 'ENDF-165', 'Void-Not Used', '', '', '', ''),
  (78, 'ENDF-164', 'R.E. Schenter', 'FTR Set 300, Multigroup Cross Sections for FTR Design', 'Oct-71', 'HEDL-TME-71-153', ''),
  (77, 'ENDF-163', 'M.R. Bhat, A. Prince', 'Evaluated Neutron Cross Sections for Ag-107, Ag-109 and Cs-133', 'Apr-73', 'BNL-50383', 'https://www.nndc.bnl.gov/endfdocs/ENDF-163.pdf'),
  (76, 'ENDF-162', 'O.D. Simpson, F.B. Simpson', 'Evaluation of the Pu-239 Cross Sections in the Resonance Region for the ENDF/B-III Data File', 'Dec-71', 'ANCR-1045', 'https://www.nndc.bnl.gov/endfdocs/ENDF-162.pdf'),
  (75, 'ENDF-161', 'J.R. Smith, R.C. Young', 'U-235 Resolved Resonance Parameters for ENDF/B-III', 'Dec-71', 'ANCR-1044', 'https://www.nndc.bnl.gov/endfdocs/ENDF-161.pdf'),
  (74, 'ENDF-160', 'A.D. MacKellar, R.E. Schenter', 'Optical Model Studies for Fast Neutron Capture Cross Section Calculations', 'Aug-72', 'HEDL-TME-71-154', ''),
  (73, 'ENDF-159', 'R.E. Schenter', 'Cross Section Evaluations of Twenty-Seven Fission Product Isotopes for...', 'Oct-71', 'HEDL-TME-71-143', ''),
  (72, 'ENDF-158', 'F.J.McCrosson, D.R.Finch, E.C.Olson', 'Testing of ENDF/B-Thermos Cross Sections for H2O, D2O, C, ZrH2, (C2H4)x, Be, Be0, C6H6, and U02', 'Oct-71', 'DP-1276', 'https://www.nndc.bnl.gov/endfdocs/ENDF-158.pdf'),
  (71, 'ENDF-157', 'M. Raymund', 'Subject:PSYCHE Code', '', '', ''),
  (70, 'ENDF-156', 'D.J. Dudziak', 'LAPHANO: P0 Multigroup Photon Production Matrix and Source Code for ENDF', 'Jan-72', 'LA-4750-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-156.pdf'),
  (69, 'ENDF-155', 'D.J. Dudziak, J.M. Romero', 'VIXEN: A Code to Check Physical Consistency of Photon-Production Data in Rived ENDF Format', 'Oct-71', 'LA-4739', 'https://www.nndc.bnl.gov/endfdocs/ENDF-155.pdf'),
  (68, 'ENDF-154', 'Void-Not Used', '', '', '', ''),
  (67, 'ENDF-153', 'B.R. Leonard Jr.', 'Thermal Cross Sections of the Fissile and Fertile Nuclei for ENDF/B-II', 'Jun-71', 'BNWL-1586', 'https://www.nndc.bnl.gov/endfdocs/ENDF-153.pdf'),
  (66, 'ENDF-152', 'H.C. Honeck, D.R. Finch', 'FLANGE II(Version 71-1). A Code to Process Thermal Neutron Data from an ENDF/B tape', 'Oct-71', 'DP-1278', 'https://www.nndc.bnl.gov/endfdocs/ENDF-152.pdf'),
  (65, 'ENDF-151', 'R.W. Roussin', 'Preparation of Data Sets in ENDF Format for Na, Mg, Cl, and K for Use in ...', 'May-71', 'ORNL/TM-3429', ''),
  (64, 'ENDF-150', 'E.H. Ottewitte, J.M. Otter, P.F. Rose, C.L. Dunford', 'An Evaluation of Ta-181 and Ta-182 for the ENDF/B Data File', 'Sep-71', 'AI-AEC-12990', 'https://www.nndc.bnl.gov/endfdocs/ENDF-150.pdf'),
  (63, 'ENDF-149', 'H. Alter', 'Evaluation of Several ENDF/B-II Cross-Section Sets Using Monte Carlo...', 'Jun-71', 'AI-AEC-13001', ''),
  (62, 'ENDF-148', 'M.R. Bhat', 'ENDF/B Processing Codes for the Resonance Region', 'Jun-71', 'BNL-50296', 'https://www.nndc.bnl.gov/endfdocs/ENDF-148.pdf'),
  (61, 'ENDF-147', 'H. Alter, R.S. Hubner', 'Status of Fast Neutron Cross Section Data Testing using ENDF/B-II DataFiles', 'May-71', 'AI-AEC-12999', ''),
  (60, 'ENDF-146 Suppl.', 'M. Raymund', 'ETOT, A Fortran-IV Program to Process Data from the ENDF/B File to Thermal Library Format', 'Nov-73', 'WCAP-7363', 'https://www.nndc.bnl.gov/endfdocs/ENDF-146-SUPP.pdf'),
  (59, 'ENDF-146', 'C.L. Beard, R.A. Dannels', 'ETOT: A Fortran IV Program to Process Data from the ENDF/B File to Thermal Library Format', 'Mar-71', 'WCAP-7363', 'https://www.nndc.bnl.gov/endfdocs/ENDF-146.pdf'),
  (58, 'ENDF-145', 'B.A. Hutchins, C.L. Cowen, M.D. Kelley, J.E. Turner', 'ENDRUN-II: A Computer Code to Generate a Generalized Multigroup Data File from ENDF/B', 'Mar-71', 'GEAP-13704', 'https://www.nndc.bnl.gov/endfdocs/ENDF-145.pdf'),
  (57, 'ENDF-144', 'A.Z. Livolsi', 'Evaluation of Tc-99 and Rh-103 Neutron Cross Sections for ENDF/B-III', 'Nov-71', 'BAW-1367', ''),
  (56, 'ENDF-143', 'R.B. Kidman, R.E. Schenter', 'Group Constants for Fast Reactor Calculations', 'Mar-71', 'HEDL-TME-71-36', ''),
  (55, 'ENDF-142', 'C.L. Thompson, J.R. Stockton, L.M. Petrie, et al.', 'EDITOR, A Processing code for ENDF/B Format Data', 'Feb-71', 'ORNL-TM-3266', 'https://www.nndc.bnl.gov/endfdocs/ENDF-142.pdf'),
  (54, 'ENDF-141', 'L. Stewart', 'Evaluated Nuclear Data for Hydrogen in the ENDF/B-II Format', 'Feb-71', 'LA-4574', 'https://www.nndc.bnl.gov/endfdocs/ENDF-141.pdf'),
  (53, 'ENDF-140', 'D.J. Dudziak', 'PHOXE: A Fortran-IV Code to Check Format Syntax, Consistency, and Physical Realism of ENDF/B Photon Production Data', 'Sep-70', 'LA-4506-MS', 'https://www.nndc.bnl.gov/endfdocs/ENDF-140.pdf'),
  (52, 'ENDF-139', 'S.K. Penny', 'A Re-Evaluation of Natural Iron Neutron and Gamma-Ray Production Cross...', 'Apr-71', 'ORNL-4617', ''),
  (51, 'ENDF-138', 'D.C. Irving', 'Evaluation of the Cross Sections of Iron: ENDF/B MAT=1101', 'Sep-70', 'ORNL/TM-2891', ''),
  (50, 'ENDF-137', 'D.C. Irving', 'LEGCK: A Subroutine to Analyze Legendre Coefficients for Negativity in the...', 'Sep-70', 'ORNL/TM-2903', ''),
  (49, 'ENDF-136', 'T.A. Pitterle', 'Evaluation of U-238 Neutron Cross Sections for the ENDF/B Version II File', 'Mar-71', 'WARD-4181-1', 'https://www.nndc.bnl.gov/endfdocs/ENDF-136.pdf'),
  (48, 'ENDF-135', 'J.T. Reynolds', 'Evaluated Neutron Cross Sections for the Zirconium Isotopes', 'Mar-70', 'KAPL-M-7078 (Restrict)', ''),
  (47, 'ENDF-134R', 'R.Q. Wright, S.N. Cramer, D.C. Irving', 'UKE-III: A Computer Program for Translating Neutron Cross Section Data From the UKAEA Nuclear Data Library ...', 'Oct-73', 'ORNL-TM-2880 REV', 'https://www.nndc.bnl.gov/endfdocs/ENDF-134R.pdf'),
  (46, 'ENDF-134', 'R.Q. Wright, S.N. Cramer, D.C. Irving', 'UKE-III: A Computer Program for Translating Neutron Cross Section ...', 'Mar-70', 'ORNL-TM-2880', ''),
  (45, 'ENDF-133', 'S. Kellman', 'Description of the Generation of Data Decks by ETOG-1 for Use in Creating...', 'Jan-70', 'WCAP-3845-2', ''),
  (44, 'ENDF-132', 'D.J. Dudziak, A.H. Marshall, R.E. Seamon', 'LAPH: A Multigroup Photon Production Matrix and Source Vector Code forENDF/B', 'May-70', 'LA-4337', 'https://www.nndc.bnl.gov/endfdocs/ENDF-132.pdf'),
  (43, 'ENDF-131', 'N.M. Green', 'An Evaluation and Compilation of the Fission and Capture Cross Sections of...', 'Feb-70', 'ORNL/TM-2797', ''),
  (42, 'ENDF-130', 'D.J. Dudziak', 'Translation to ENDF/B and &quot;Physics&quot; Checking of Cross Sections for Shielding', 'Nov-69', 'DASA-2379', 'https://www.nndc.bnl.gov/endfdocs/ENDF-130.pdf'),
  (41, 'ENDF-129', 'N. Azziz', 'Iron, Nickel, and Chromium Neutron Cross Sections from 0-15 MeV', 'Aug-69', 'WCAP-7281', ''),
  (40, 'ENDF-128', 'D.J. Dudziak, J.M. Cook', 'LUTE and LATEX, Special-Purpose Codes to Translate from Modified UK to ENDF/B Format', 'Aug-69', 'NE-3383-102-69U', 'https://www.nndc.bnl.gov/endfdocs/ENDF-128.pdf'),
  (39, 'ENDF-127', 'R.E. Schenter', 'ETOX-A. Code to Calculate Group Constants for Nuclear Reactor Calculations', 'May-69', 'BNWL-1002', 'https://www.nndc.bnl.gov/endfdocs/ENDF-127.pdf'),
  (38, 'ENDF-126', 'C.L. Dunford ,R.F. Berland, R.S. Hubner, R.J. Creasy', 'SCORE II-An Interactive Neutron Evaluation System', 'Mar-69', 'AI-AEC-12757', 'https://www.nndc.bnl.gov/endfdocs/ENDF-126.pdf'),
  (37, 'ENDF-125', 'E.M. Pennington', 'ENDF/B Neutron Cross Section Data for Natural Helium', 'Oct-68', 'ANL-7462', 'https://www.nndc.bnl.gov/endfdocs/ENDF-125.pdf'),
  (36, 'ENDF-124', 'J.M. Otter, R.S. Hubner, R.W. Campbell, et al.', 'Evaluated Neutron Cross Sections forCu-63, Cu-65, and Natural Cu', 'Dec-68', 'AI-AEC-12741', 'https://www.nndc.bnl.gov/endfdocs/ENDF-124.pdf'),
  (35, 'ENDF-123', 'J.T. Reynolds', 'Evaluated Neutron Cross Sections for the Gadolinium Isotopes', 'May-68', 'KAPL-3416 (Restrict)', ''),
  (34, 'ENDF-122', 'T.A. Pitterle, M. Yamamoto', 'Evaluated Neutron Cross Sections of Pu-240 for the ENDF/B File', 'Jun-68', 'APDA-218', 'https://www.nndc.bnl.gov/endfdocs/ENDF-122.pdf'),
  (33, 'ENDF-121', 'T.A. Pitterle', 'Evaluated Neutron Cross Sections of Sodium-23 for the ENDF/B File', 'Jun-68', 'APDA-217', 'https://www.nndc.bnl.gov/endfdocs/ENDF-121.pdf'),
  (32, 'ENDF-120', 'D.M. Green, T.A. Pitterle', 'ETOE-A Program for ENDF/B to MC2 Data Conversion', 'Jun-68', 'APDA-219', 'https://www.nndc.bnl.gov/endfdocs/ENDF-120.pdf'),
  (31, 'ENDF-119', 'Void See ENDF-133', '', '', '', ''),
  (30, 'ENDF-118', 'Void See ENDF-133', '', '', '', ''),
  (29, 'ENDF-117', 'J.R. Smith', 'Subject:Am-241,Am-243', '', '', ''),
  (28, 'ENDF-116', 'J.R. Smith, R.A. Grimesey', 'An Evaluation and Compilation of Np-237 Cross Section Data for the ENDF/B File', 'May-69', 'IN-1182', 'https://www.nndc.bnl.gov/endfdocs/ENDF-116.pdf'),
  (27, 'ENDF-115', 'W.B. Henderson', 'Evaluation of Re-185 and Re-187 Neutron Cross Sections for ENDF/B', 'Mar-68', 'GEMP-587', ''),
  (26, 'ENDF-114 Suppl.', 'M. Raymund', 'ETOG-1-A Fortran IV Program to Process Data from the ENDF/B File to the MUFT, GAM and ANISN Formats', 'Aug-73', 'WCAP-3845-1 Suppl.1', 'https://www.nndc.bnl.gov/endfdocs/ENDF-114-SUPP.pdf'),
  (25, 'ENDF-114', 'D.E. Kusner, S. Kellman', 'ETOG-1-A Fortran IV Program to Process Data from the ENDF/B File to the MUFT,GAM and ANISN Formats', 'Dec-69', 'WCAP-3845-1', 'https://www.nndc.bnl.gov/endfdocs/ENDF-114.pdf'),
  (24, 'ENDF-113', 'R.A. Dannels, D.E. Kusner', 'ETOM-1-A Fortran IV Program to Process Data from the ENDF/B File to the MUFT Format', 'May-68', 'WCAP-3688-1', 'https://www.nndc.bnl.gov/endfdocs/ENDF-113.pdf'),
  (23, 'ENDF-112', 'J.T. Reynolds, C.R. Lubitz', 'Evaluated Cross Sections for the Hafnium Isotopes', 'Aug-67', 'KAPL-3327 (Restrict)', 'https://www.nndc.bnl.gov/endfdocs/ENDF-112.pdf'),
  (22, 'ENDF-111', 'D.J. Dudziak', 'ENDF/B Format Requirements for Shielding Applications', 'Apr-67', 'LA-3801', 'https://www.nndc.bnl.gov/endfdocs/ENDF-111.pdf'),
  (21, 'ENDF-110', 'O. Ozer', 'Description of the ENDF/B Processing Codes and Retrieval Subroutines', 'Jun-71', 'BNL-50300', 'https://www.nndc.bnl.gov/endfdocs/ENDF-110.pdf'),
  (20, 'ENDF-109', 'D.C. Irving', 'Evaluation of Neutron Cross Sections for Boron-10', 'Oct-67', 'ORNL/TM-1872', ''),
  (19, 'ENDF-108', 'M.K. Drake', 'Handwritten Notes of Be, U-234, U-236, Pu-241 for ENDF/B', '', '', ''),
  (18, 'ENDF-107', 'Void-Not Used', '', '', '', ''),
  (17, 'ENDF-106', 'C.L. Dunford, R.F. Berland, R.J. Creasy', 'SCORE - An Automated Cross Section Evaluation System', 'Jan-68', 'NAA-SR-MEMO-12529', 'https://www.nndc.bnl.gov/endfdocs/ENDF-106.pdf'),
  (16, 'ENDF-105', 'R.S. Hubner, B.J. Lemke', 'EDIT-A Fortran IV level H Program to Punch, Print, and Plot Selected Portions of an ENDF/B Data Tape', 'Nov-67', 'NAA-SR-12525', 'https://www.nndc.bnl.gov/endfdocs/ENDF-105.pdf'),
  (15, 'ENDF-104', 'W.A. Wittkopf', 'Th-232 Neutron Cross Section Data for the ENDF/B', '', '', ''),
  (14, 'ENDF-103', 'W.A. Wittkopf, D.H. Roy, A.Z. Livolsi', 'U-238 Neutron Cross-Section Data for the ENDF/B', 'May-67', 'BAW-316', 'https://www.nndc.bnl.gov/endfdocs/ENDF-103.pdf'),
  (12, 'ENDF-102 1997', 'V. McLane, C.L. Dunford, P.F. Rose', 'Data Formats and Procedures for the Evaluated Nuclear Data File ENDF-6', 'Feb-97', 'BNL-NCS-44945 REV.2/97', 'https://www.nndc.bnl.gov/endfdocs/ENDF-102-1997.pdf'),
  (11, 'ENDF-102 1995', 'V. McLane, C.L. Dunford, P.F. Rose', 'Data Formats and Procedures for the Evaluated Nuclear Data File ENDF-6', 'Nov-95', 'BNL-NCS-44945 REV.11/95', 'https://www.nndc.bnl.gov/endfdocs/ENDF-102-1995.pdf'),
  (10, 'ENDF-102 1991', 'P.F. Rose, C.L. Dunford', 'Data Formats and Procedures for the Evaluated Nuclear Data File ENDF-6', 'Oct-91', 'BNL-NCS-44945 REV', ''),
  (9, 'ENDF-102 1990', 'P.F. Rose, C.L. Dunford', 'Data Formats and Procedures for the Evaluated Nuclear Data File ENDF-6', 'Jul-90', 'BNL-NCS-44945', ''),
  (8, 'ENDF-102 1983', 'B.A. Magurno', 'Data Formats and Procedures for the Evaluated Nuclear Data File,ENDF.V-V', 'Nov-83', 'BNL-NCS-50496 2 Ed. Rev.', 'https://www.nndc.bnl.gov/endfdocs/ENDF-102-1983.pdf'),
  (7, 'ENDF-102 1980', 'S. Pearlstein', 'Supp. to the ENDF/B-V Formats and Procedures Manual for Using ENDF/B-IV ...', 'Nov-80', 'BNL-NCS-28949 2 Ed. Suppl.', ''),
  (6, 'ENDF-102 1979', 'R.R. Kinsey', 'Data Formats and Procedures for the Evaluated Nuclear Data File, ENDF/B-V', 'Oct-79', 'BNL-NCS-50496 3 Ed.', ''),
  (5, 'ENDF-102 1975', 'D.I. Garber', 'Data Formats and Procedures for Evaluated Nuclear Data File', 'Oct-75', 'BNL-NCS-50496 2 Ed.', 'https://www.nndc.bnl.gov/endfdocs/ENDF-102-1975.pdf'),
  (4, 'ENDF-102 1970 Vol.2', 'D.J. Dudziak', 'ENDF Formats and Procedures for Photon Production and Interaction Data', 'Jul-71', 'LA-4549 1st Ed. Vol.2', 'https://www.nndc.bnl.gov/endfdocs/ENDF-102-1970-2.pdf'),
  (3, 'ENDF-102 1970 Vol.1', 'M.K. Drake', 'Data Formats and Procedures for the ENDF Neutron Cross Section Library', 'Oct-70', 'BNL-50274 1st Ed. Vol.1', 'https://www.nndc.bnl.gov/endfdocs/ENDF-102-1970-1.pdf'),
  (2, 'ENDF-102 1966', 'H.C. Honeck', 'Specifications for an Evaluated Nuclear Data File for REACTOR APPLICATION...', 'May-66', 'BNL-50066 1st Ed.', 'https://www.nndc.bnl.gov/endfdocs/ENDF-102-1966.pdf'),
  (1, 'ENDF-101', 'T.E. Stephenson, A. Prince, S. Pearlstein', 'Evaluation of the Neutron Cross Section of Manganese for the ENDF/B Library', 'Jun-67', 'BNL-50060', ''),
  (0, 'BNL-8381', 'H.C. Honeck', 'ENDF: Evaluated Nuclear Data File Description and Specifications', 'Jan-65', 'BNL-8381', 'https://www.nndc.bnl.gov/endfdocs/BNL-8381.pdf');
